/** @type {import('tailwindcss').Config} */

/** Keep in sync with MATERIAL_ROLE_NAMES and CUSTOM_ROLE_NAMES in src/config/themeTokens.ts. */
const schemeRoles = [
  'primary',
  'on-primary',
  'primary-container',
  'on-primary-container',
  'inverse-primary',
  'primary-fixed',
  'primary-fixed-dim',
  'on-primary-fixed',
  'on-primary-fixed-variant',
  'secondary',
  'on-secondary',
  'secondary-container',
  'on-secondary-container',
  'secondary-fixed',
  'secondary-fixed-dim',
  'on-secondary-fixed',
  'on-secondary-fixed-variant',
  'tertiary',
  'on-tertiary',
  'tertiary-container',
  'on-tertiary-container',
  'tertiary-fixed',
  'tertiary-fixed-dim',
  'on-tertiary-fixed',
  'on-tertiary-fixed-variant',
  'error',
  'on-error',
  'error-container',
  'on-error-container',
  'background',
  'on-background',
  'surface',
  'surface-dim',
  'surface-bright',
  'surface-container-lowest',
  'surface-container-low',
  'surface-container',
  'surface-container-high',
  'surface-container-highest',
  'surface-variant',
  'on-surface',
  'on-surface-variant',
  'outline',
  'outline-variant',
  'inverse-surface',
  'inverse-on-surface',
  'shadow',
  'scrim',
  'surface-tint',
  'success',
  'on-success',
  'success-container',
  'on-success-container',
  'warning',
  'on-warning',
  'warning-container',
  'on-warning-container',
  'info',
  'on-info',
  'info-container',
  'on-info-container',
];

const schemeColors = Object.fromEntries(
  schemeRoles.map((role) => [role, `var(--md-sys-color-${role})`]),
);

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: ['selector', '[data-mode="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['IBM Plex Sans', 'system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        ...schemeColors,
        'editor-primary': schemeColors.primary,
        'editor-on-primary': schemeColors['on-primary'],
        'editor-background': schemeColors.surface,
        'editor-surface': schemeColors['surface-container-low'],
        'editor-text': schemeColors['on-surface'],
        'editor-muted': schemeColors['on-surface-variant'],
        'editor-border': schemeColors['outline-variant'],
        text: schemeColors['on-surface'],
        'text-secondary': schemeColors['on-surface-variant'],
        border: schemeColors['outline-variant'],
      },
    },
  },
  plugins: [],
};
